name: Terraform Azure CI/CD

on:
  push:
    branches:
      - main
      - 'feature/**'

  pull_request:
    branches:
      - main

permissions:
  contents: read

jobs:
  terraform:
    name: Terraform CI/CD
    runs-on: self-hosted

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Add Terraform to PATH
        shell: powershell
        run: |
          $terraformPath = "C:\Users\harsh.sharma\AppData\Local\Microsoft\WinGet\Packages\Hashicorp.Terraform_Microsoft.Winget.Source_8wekyb3d8bbwe"
          Add-Content -Path $env:GITHUB_PATH -Value $terraformPath

      - name: Check Terraform Version
        shell: powershell
        run: |
          where.exe terraform
          terraform version

      - name: Check Azure CLI
        run: az version

      - name: Check Azure Account
        run: az account show

      - name: Terraform Init
        run: terraform init

      - name: Terraform Format Check
        run: terraform fmt -check -recursive

      - name: Terraform Validate
        run: terraform validate

      - name: Terraform Plan
        run: terraform plan

      - name: Terraform Apply
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        run: terraform apply -auto-approve